// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	gorm2 "gorm.io/gorm"
	"nonelandBackendInterview/configs"
	"nonelandBackendInterview/internal/db"
	"nonelandBackendInterview/internal/entity"
	"nonelandBackendInterview/internal/repo/gorm"
	"sync"
)

// Injectors from wire.go:

func NewRepo() (entity.Repository, error) {
	db := NewDB()
	config := NewConfig()
	repository := gorm.NewRepository(db, config)
	return repository, nil
}

// wire.go:

var cg *configs.Config

var configOnce sync.Once

func NewConfig() *configs.Config {
	configOnce.Do(func() {
		cg = configs.NewConfig()
	})

	return cg
}

var database *gorm2.DB

var dbOnce sync.Once

func NewDB() *gorm2.DB {
	dbOnce.Do(func() {
		database = db.NewDb()
	})

	return database
}
